//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenDigital.Android.ApiBrowser
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_tab_albums = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_albums_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_albums_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_artists = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_artists_grey = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_artists_white = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_songs = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_songs_grey = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_songs_white = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int entry = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int label = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int result = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int results = 2131034115;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main_tab = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
